spring.application.name=aulas
server.port=8080
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
firebase.credentials.path=firebase-credentials.json
firebase.database.url=https//reservas-aulas-default-rtdb.firebaseio.com
logging.level.com.reservas=DEBUG
